name: PHP Run

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP Action
      uses: shivammathur/setup-php@2.1.4
      
    - name: Run
      run: php index.php > output.md
      
    - name: Upload file
      uses: actions/upload-artifact@v1
      with:
           name: output
           path: output.md
